version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    commit-message:
      prefix: "MESH-2092 "
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    groups:
      patch-and-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "MESH-2092 "
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    groups:
      patch-and-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"
