version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    commit-message:
      prefix: "MESH-2092 "
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "MESH-2092 "
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 7
